# Spring config
management:
  endpoint:
    metrics:
      enabled: true
    web:
      exposure:
        include: metrics
spring:
  mvc:
    static-path-pattern: /static
    throw-exception-if-no-handler-found: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect: Oracle12cDialect
  logging:
    level:
      org.springframework.boot.autoconfigure.jdbc: DEBUG
      com.zaxxer.hikari: DEBUG
  servlet:
    multipart:
      max-file-size: 30MB
  datasource:
    #    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      autoCommit: true
      keepaliveTime: 300000
      minimumIdle: 3
      maximumPoolSize: 25
      idleTimeout: 600000 # maximum idle time for connection
      connectionTimeout: 30000 # maximum number of milliseconds that a client will wait for a connection
      max-lifetime: 1080000
      poolName: ecms-product-main-pool
      leak-detection-threshold: 2000
    backend:
      jdbcUrl: ${BACKEND_DB_URL:jdbc:oracle:thin:@124.43.16.185:50170:cmsbkdb}
      username: ${BACKEND_USERNAME:CMSPRODUCTBACKEND}
      password: ${BACKEND_PASSWORD:password}
      driverClassName: oracle.jdbc.driver.OracleDriver
      test-on-borrow: true
      validationQuery: SELECT 1 FROM DUAL
    online:
      jdbcUrl: ${BACKEND_DB_URL:jdbc:oracle:thin:@124.43.16.185:50170:cmsbkdb}
      username: ${BACKEND_USERNAME:CMSPRODUCTONLINE}
      password: ${BACKEND_PASSWORD:password}
      driverClassName: oracle.jdbc.driver.OracleDriver
      test-on-borrow: true
      validationQuery: SELECT 1 FROM DUAL
jwt:
  issuer: epic-cms
  secret: EPICCMSREVAMP
  token-validity: 36000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method

#Report module DB Connections
ecms_issuing_report_backend_connection_url : CMSPRODUCTBACKEND/password@//124.43.16.185:50170/cmsbkdb
ecms_issuing_report_online_connection_url : CMSPRODUCTONLINE/password@//124.43.16.185:50170/cmsbkdb

#EOD File upload path
eoduploadpath: '/CMS/EODFILE/'

